"""R10 — About, Privacy and "The four responses" pages."""

from tests.web_helpers import client


def get(path: str) -> str:
    response = client().get(path)
    assert response.status_code == 200
    return response.text.replace("&#39;", "'")


def test_r10_about_states_ai_drafted_and_human_approved() -> None:
    assert "Scenarios are AI-drafted, then fact-checked and approved by a human" in get("/about")


def test_r10_about_states_coaching_comes_from_learners_assistant() -> None:
    assert "generated by your own AI assistant, not by this site" in get("/about")


def test_r10_about_states_no_isc2_affiliation() -> None:
    assert "not affiliated with or endorsed by ISC2" in get("/about")


def test_r10_privacy_states_single_session_cookie() -> None:
    assert (
        "The site sets one session cookie. It's used only to protect form submissions, "
        "with no tracking."
    ) in get("/privacy")


def test_r10_privacy_lists_each_data_item_with_retention() -> None:
    html = get("/privacy")
    for row_id, retention in [
        ("privacy-attempts", "180 days"),
        ("privacy-aggregates", "Kept"),
        ("privacy-free-text", "Never stored or logged"),
        ("privacy-logs", "14 days"),
        ("privacy-cdn", "Standard logging is turned off"),
        ("privacy-waf", "Up to 3 hours"),
        ("privacy-ci", "No learner data"),
    ]:
        start = html.index(f'id="{row_id}"')
        assert retention in html[start : html.index("</tr>", start)], row_id


def test_r10_responses_page_covers_four_responses_and_five_treatments() -> None:
    html = get("/responses")
    for response in ("avoid", "mitigate", "transfer", "accept"):
        assert f'id="response-{response}"' in html
    for label in ('Mitigate: remediate ("fix")', 'Mitigate: compensating control ("reduce")'):
        assert label.replace('"', "&#34;") in html or label in html
    assert "Ignoring a risk is not one of them." in html


def test_r10_every_page_links_about_and_privacy() -> None:
    html = get("/")
    assert 'href="/about"' in html
    assert 'href="/privacy"' in html
